
GET http://localhost:8000/

###

POST http://localhost:8000/user/register/
Content-Type: application/json

{
    "firstName": "Anna",
    "lastName": "Burger",
    "phoneNumber": 1234567890,
    "password": "pass123",
    "mailingAddress": "123 Main",
    "billingAddress": "123 Main"

}

###
POST   http://localhost:8000/user/login
Content-Type: application/json

{
    "phoneNumber": 1234567890,
    "password": "pass123"
}

