
GET http://localhost:8000/

###

POST http://localhost:8000/user/register/
Content-Type: application/json

{
    "firstName": "VoB",
    "lastName": "Burger",
    "phoneRegister": "+1 234 566 7777",
    "passwordRegister": "pass123"

}

###
POST   http://localhost:8000/user/login
Content-Type: application/json

{
    "phoneLogin": "+1 234 566 7777",
    "passwordLogin": "pass123"
}

