GET http://localhost:3000/login

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "FirstName": "Anna",
    "LastName": "Burger",
    "PhoneNumber": "22",
    "Password": "aaa" 
}